### ISSUE TITLE
Result refresh - reads payload with a wrong identifier

### ISSUE THREAD

**Issue by shofinetz** [RegioHelden/django-datawatch#15]
identifier currently used - id of the Result object.
Fix: use the identifier of Result object

**Comment by lociii** [comment]
Are you talking about post_save updates or which refresh is wrong?

**Comment by shofinetz** [comment]
Whenever trigering the Refresh from the Result page: right corner in the: actions list of 'Acknowledge', 'Change config', 'Refresh'

**Comment by lociii** [comment]
The referenced commit should fix this issue
